---
name: hello-world
on:
  repository_dispatch: # registers event listener
    types: [start-workflow] # type(s) of events to listen to
jobs:
  example:
    steps:
      - name: Echo Hello World
        shell: bash
        run:  echo "Hello World!"
